// Code generated manually for interface: Deleter
package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// Deleter is an autogenerated mock type for the Deleter interface
type Deleter struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: alias
func (_m *Deleter) DeleteURL(alias string) error {
	ret := _m.Called(alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleter interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleter creates a new instance of Deleter. It also registers a testing interface on the mock and a cleanup function to assert the mock's expectations.
func NewDeleter(t mockConstructorTestingTNewDeleter) *Deleter {
	mock := &Deleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
